name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Image
      run: |
        docker build -t antonyjebinraj/hello-app:latest .
        docker push antonyjebinraj/hello-app:latest

    - name: Security Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: antonyjebinraj/hello-app:latest
        severity: HIGH,CRITICAL
        exit-code: 1

    - name: Deploy via Helm
      run: |
        helm upgrade --install hello-app ./helm/hello-app
